### ISSUE TITLE
Don't require PKCL12 to be a string file path

### ISSUE THREAD

**Issue by xiongtx** [aphyr/less-awful-ssl#14]
The type hint [here](https://github.com/aphyr/less-awful-ssl/blob/7c62d52a9df48d774dc373be888dec3514051796/src/less/awful/ssl.clj#L154) prevents the use of a `File`, which is what we'd get if we used `(-> <name.p12> io/resource io/file)`.

**Comment by aphyr** [comment]
Sure, feel free to add a PR that does an appropriate coercion there. Just as long as we avoid the reflector; feel free to do dynamic type checks if that's easier. :)
