### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by middlesphere** [aphyr/less-awful-ssl#9]
Hello.

In less-awful-ssl is used code (SSLContext/getInstance "TLS") which return SSL not TLS connection under some circumstances. SSL is not secure anymore and TLS 1.1 is not enough. 
Reason of this behaviour described here:
https://stackoverflow.com/questions/29841610/will-sslcontext-getinstancetls-supports-tls-v1-1-and-tls-v1-2-also 

and here:
https://stackoverflow.com/questions/1037590/which-cipher-suites-to-enable-for-ssl-socket/23365536#23365536

Can you make an update and put (SSLContext/getInstance "TLSv1.2")

Thanks.

**Comment by Vitexus** [comment]
We also need it so much :disappointed: 
In case of pull request would somebody (@aphyr) accept it ?

**Comment by aphyr** [comment]
Go for it!

**Comment by aphyr** [comment]
Fixed in 1.0.6, available on Clojars now.
